import type { Metadata } from "next"
import { DM_Sans } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "next-themes"
import Footer from "@/components/layout/footer"
import Navbar from "@/components/layout/navbar"
import ToastProvider from "@/components/custom/toast-provider"

const font = DM_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={font.className}>
        <ThemeProvider attribute='class'>
          <Navbar />
          <main className='bg-gradient-to-b from-blue-400 via-orange-400 to-rose-800'>
            <ToastProvider />
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
